stages:
  - test
  - build

test:
  stage: test
  image: node:15.7.0
  script:
    - yarn
    - yarn build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - |
      /kaniko/executor \
      --context ${CI_PROJECT_DIR} \
      --dockerfile ${CI_PROJECT_DIR}/Dockerfile \
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHORT_SHA}-$(date +%s) \
      --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  only:
    - master
    - tags
