version: '3.8'
services:
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
  psql:
    image: 'postgres:13'
    command:
      - /bin/sh
      - -c
      - |
        sleep 10
        psql --host=postgres --username=user -w < /var/pg-testdata.sql
    volumes:
      - ${PWD}/pg-testdata.sql:/var/pg-testdata.sql
    environment:
      PGPASSWORD: 'password'
  polkabtc:
    image: 'registry.gitlab.com/interlay/btc-parachain/standalone:0.6.1'
    command:
      - btc-parachain
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --rpc-methods
      - Unsafe
      - --dev
    ports:
      - '9933:9933'
      - '9944:9944'
  # electrs:
  #   image: 'interlayhq/electrs:latest'
  #   command:
  #     - electrs
  #     - -v
  #     - --network
  #     - regtest
  #     - --jsonrpc-import
  #     - --cors
  #     - '*'
  #     - --cookie
  #     - 'rpcuser:rpcpassword'
  #     - --daemon-rpc-addr
  #     - bitcoind:18443
  #     - --http-addr
  #     - '[::0]:3002'
  #     - --index-unspendables
  #   ports:
  #     - '3002:3002'
